/**
 * Bundle assembler for the browser-only mobile companion plugin.
 *
 * Emits the closure-factory artifact the dsh web module loader expects:
 * the bundle calls window.__ModuleLoader__.load({id, factory}) and the
 * factory body is plain CJS (module.exports). The stylesheet is embedded
 * and injected as a <style data-plugin> tag at factory execution — the
 * loader removes plugin-owned tags on unload. No external runtime
 * imports, so no externals table and no bundler dependency: plain Node.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = dirname(fileURLToPath(import.meta.url))
const id = '@dsh-external/dsh-client-ui-mobile-companion'

const css = readFileSync(join(root, 'src/client/mobile.css'), 'utf8')
const body = readFileSync(join(root, 'src/client/index.js'), 'utf8')

const bundle = `/*! ${id} client bundle — generated by build.mjs, do not edit */
window.__ModuleLoader__.load({ id: ${JSON.stringify(id)}, factory: (require) => {
var module = { exports: {} }; var exports = module.exports;
;(function installPluginCss() {
  var css = ${JSON.stringify(css)};
  var tagId = ${JSON.stringify(`${id}/mobile.css`)};
  if (typeof document !== 'undefined' && document.querySelector('style[data-plugin-css=' + JSON.stringify(tagId) + ']') === null) {
    var tag = document.createElement('style');
    tag.dataset.plugin = ${JSON.stringify(id)};
    tag.dataset.pluginCss = tagId;
    tag.textContent = css;
    document.head.appendChild(tag);
  }
})();
${body}
return module.exports; } });
`

mkdirSync(join(root, 'lib'), { recursive: true })
writeFileSync(join(root, 'lib/client.js'), bundle)
console.log(`wrote lib/client.js (${bundle.length} bytes)`)
